service: serverless-task 

provider:
  name: aws
  runtime: python3.7
  versionFunctions: false
  memorySize: 1024
  region: us-east-1
  deploymentBucket:
    name: 'serverless-bitwala-bucket'
  role: arn:aws:iam::600178069412:role/lambda_execution_role
  token: none

plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
functions: 
  gethelloWorld:
    handler: lambda/helloworld.helloworld
    events:
        - http:
            path: helloWorld/
            method: get
        - sns:
            arn: !Ref lambdaAlert
            topicName: LambdaSNS

resources:
  Resources:
    lambdaAlert :
      Type: AWS::SNS::Topic
      Properties:
        TopicName: LambdaSNS 

